# -*- coding: utf-8 -*-
from odoo import models, fields, api, Command,exceptions, _
from odoo.fields import Command
from cryptography.fernet import Fernet
import base64
import time
import requests
from werkzeug import urls
from odoo.addons.payment.controllers.post_processing import PaymentPostProcessing

class CourseReferral(models.Model):
    _name = 'apg.course.referral'
    _description = 'Course Referral'
    _rec_name = 'course_id'

    course_id = fields.Many2one('slide.channel', string="Course")
    expiry_time = fields.Char('Expiry Time')
    website_url = fields.Char(string="Cours Url", related='course_id.website_url')
    partner_id = fields.Many2one('res.partner', string="Generated By", ondelete="cascade")
    generated_url = fields.Char(string="Generated URL")
    payment_link = fields.Char(string="Payment Link")
    order_id  = fields.Many2one('sale.order', string="Sale Order", ondelete="cascade")
    stage_id = fields.Many2one('slide.channel.upgrade.stage')
    
    def generate_referral_link(self):
        key1 = self.env['ir.config_parameter'].sudo().get_param('apg_course_referral.apg_encryption_key')
        key = key1.encode('utf-8')  # Same as in controller
        cipher_suite = Fernet(key)
        course_id = str(self.course_id.id)
        partner_id = str(self.partner_id.id)
        course_url = str(self.website_url)
        expiry_time = int(time.time()) + int(self.expiry_time)
        stage_id = str(self.stage_id.id)
        data = f"{course_id}|{partner_id}|{course_url}|{expiry_time}|{stage_id}"
        encrypted_bytes = cipher_suite.encrypt(data.encode('utf-8'))
        encrypted_token = base64.urlsafe_b64encode(encrypted_bytes).decode('utf-8')
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        self.generated_url = f"{base_url}/referral/{encrypted_token}"
        return self.generated_url
        # return f"{base_url}/referral/{encrypted_token}"

    def generate_payment_link(self):
        """Creates a payment link for this sales order."""
        key1 = self.env['ir.config_parameter'].sudo().get_param('apg_course_referral.apg_encryption_key')
        key = key1.encode('utf-8')  # Same as in controller
        cipher_suite = Fernet(key)
        course_id = str(self.course_id.id)
        partner_id = str(self.partner_id.id)
        course_url = str(self.website_url)
        expiry_time = int(time.time()) + int(self.expiry_time)
        stage_id = str(self.stage_id.id)
        data = f"{course_id}|{partner_id}|{course_url}|{expiry_time}|{stage_id}"
        encrypted_bytes = cipher_suite.encrypt(data.encode('utf-8'))
        encrypted_token = base64.urlsafe_b64encode(encrypted_bytes).decode('utf-8')
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        self.generated_url = f"{base_url}/payment/{encrypted_token}"
        return self.generated_url

    def create_trasaction(self,order=False,provider=False):
        vals = {
            "reference": order.name,
            "amount": order.amount_total,
            "provider_id": provider.id,
            "payment_method_id": 151,
            "partner_id": order.partner_id.id,
            'is_post_processed': True,
            'sale_order_ids': [Command.set([order.id])],  # Pass IDs instead of recordset
            'currency_id': self.env.company.currency_id.id,
            'landing_route': '/shop/payment/validate',
        }
        tx_sudo = self.env['payment.transaction'].sudo().create(vals)
        PaymentPostProcessing.monitor_transaction(tx_sudo)
        return tx_sudo
    
              

class MyProductCart(models.Model):
    _inherit = 'my.product.cart'
    _description = 'My Product Cart'

    referral_id = fields.Many2one('apg.course.referral')