# -*- coding: utf-8 -*-
from odoo import models, fields, api, Command,exceptions, _
from odoo.fields import Command
from cryptography.fernet import Fernet
import base64
import time
import requests
from werkzeug import urls
from odoo.addons.payment.controllers.post_processing import PaymentPostProcessing

class CourseReferral(models.Model):
    _name = 'apg.course.referral'
    _description = 'Course Referral'
    _rec_name = 'course_id'

    course_id = fields.Many2one('slide.channel', string="Course")
    expiry_time = fields.Char('Expiry Time')
    website_url = fields.Char(string="Cours Url", related='course_id.website_url')
    partner_id = fields.Many2one('res.partner', string="Generated By", ondelete="cascade")
    generated_url = fields.Char(string="Generated URL")
    payment_link = fields.Char(string="Payment Link")
    order_id  = fields.Many2one('sale.order', string="Sale Order", ondelete="cascade")
    stage_id = fields.Many2one('slide.channel.upgrade.stage')
    
    def generate_referral_link(self):
        key1 = self.env['ir.config_parameter'].sudo().get_param('apg_course_referral.apg_encryption_key')
        key = key1.encode('utf-8')  # Same as in controller
        cipher_suite = Fernet(key)
        course_id = str(self.course_id.id)
        partner_id = str(self.partner_id.id)
        course_url = str(self.website_url)
        expiry_time = int(time.time()) + int(self.expiry_time)
        stage_id = str(self.stage_id.id)
        data = f"{course_id}|{partner_id}|{course_url}|{expiry_time}|{stage_id}"
        encrypted_bytes = cipher_suite.encrypt(data.encode('utf-8'))
        encrypted_token = base64.urlsafe_b64encode(encrypted_bytes).decode('utf-8')
        base_url = self.env['ir.config_parameter'].sudo().get_param('web.base.url')
        self.generated_url = f"{base_url}/referral/{encrypted_token}"
        return self.generated_url
        # return f"{base_url}/referral/{encrypted_token}"

    def generate_payment_link(self,order=False,partner_name=False,partner_email=False):
        """Creates a payment link for this sales order."""
        return_url = '/payment/instamojo/return'
        provider_id = self.env['payment.provider'].sudo().search([('code', '=', 'instamojo_checkout')])
        if not provider_id:
            raise exceptions.ValidationError(_("Payment provider not found."))

        if not order:
            raise exceptions.ValidationError(_("Order not found."))

        tx_id = self.create_trasaction(order,provider_id)
        print("Transaction Id: ", tx_id)
        token = requests.post('https://api.instamojo.com/oauth2/token/', data={
            'grant_type': 'client_credentials',
            'client_id': provider_id.instamojo_client_id,
            'client_secret': provider_id.instamojo_client_secret,
        })
        access_token = token.json()["access_token"]
        headers = { 
          "Authorization": f'Bearer {access_token}'
        }
        try:
            website = self.env['website'].sudo().get_current_website()
            base_url = website.get_base_url()
        except:
            base_url = self.get_base_url()

        payload = {
            "amount": order.amount_total,
            "purpose": order.name,
            "buyer_name": partner_name,
            "email": partner_email,
            'redirect_url': urls.url_join(base_url, return_url) + '?reference=%s' % order.name,
            # "webhook": f"https://yourwebsite.com/payment/webhook",
            "allow_repeated_payments": False
        }
        response = requests.post(
            "https://api.instamojo.com/v2/payment_requests/",
            data=payload,
            headers=headers
        )
        if response.status_code == 201:
            payment_data = response.json()
            self.payment_link = payment_data['longurl']

    def create_trasaction(self,order=False,provider=False):
        vals = {
            "reference": order.name,
            "amount": order.amount_total,
            "provider_id": provider.id,
            "payment_method_id": 151,
            "partner_id": order.partner_id.id,
            'is_post_processed': True,
            'sale_order_ids': [Command.set([order.id])],  # Pass IDs instead of recordset
            'currency_id': self.env.company.currency_id.id,
            'landing_route': '/shop/payment/validate',
        }
        tx_sudo = self.env['payment.transaction'].sudo().create(vals)
        PaymentPostProcessing.monitor_transaction(tx_sudo)
        return tx_sudo
    
              

class MyProductCart(models.Model):
    _inherit = 'my.product.cart'
    _description = 'My Product Cart'

    referral_id = fields.Many2one('apg.course.referral')