# -*- coding: utf-8 -*-
{
    'name': 'Kreator website',
    'version': '18.0.0.0.1',
    'category': 'Website',
    'summary': 'Enable portal users to create eLearning courses',
    'description': 'A module allowing portal users to create courses for the eLearning module in the backend.',
    'author': 'Your Name',
    'website': 'https://yourwebsite.com',
    'depends': ['website', 'web', 'apg_js', 'website_slides', 'website_sale_slides', 'apg_elearning', 'website_sale',
                'crm', 'mail', 'loyalty'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/get_started.xml',
        # 'views/1getstart.xml',
        # 'views/maindesign.xml',
        # 'views/course_details.xml',
        'views/slide_menu_template.xml',
        # 'views/custom_404_template.xml',
        'views/Ncourse_standard.xml',
        'views/Nterm.xml',
        # 'views/welcome.xml',
        'views/Nkyc.xml',
        'views/nincome_data.xml',
        'views/nreferral.xml',
        'views/nleaderboard.xml',
        'views/nmy_courses.xml',
        'views/ntarget.xml',
        # 'views/partner.xml',
        'views/partner1.xml',
        'views/nmy_courses_partner.xml',
        'views/npromote.xml',
        # 'views/fbpost.xml',
        'views/offers.xml',
        # 'views/maintemp.xml',
        'views/master.xml',
        'views/master_course_detail.xml',
        'views/master_course_standard.xml',
        'views/master_term.xml',
        'views/master_welcome.xml',
        'views/customer_courses.xml',
        'views/customer_recommend.xml',
        'views/master_income_data.xml',
        # 'views/webtemp.xml',
        # 'views/creator_dashboard.xml',
        # 'views/partner_webtemp.xml',
        # 'views/partner_dashboard.xml',
        # 'views/customer_webtemp.xml',
        # 'views/customer_dashboard.xml',
        'views/choose_product.xml',
        'views/partner_products.xml',
        'views/myproduct_new.xml',
        'views/promotional.xml',
        'views/partner_kyc.xml',
        # 'views/boot5.xml',
        'views/partner_lead.xml',
        'views/coupon.xml',
        'views/choose_product_detail.xml',
        'views/creator_lead.xml',
        'views/partner_income_data.xml',
        'views/creator_landing_page_js.xml',
        'views/edit_landing_page.xml',
        'views/landing_page_template1.xml',
        # 'views/partner_refferal.xml',
        'views/partner_leaderboard.xml',
        'views/partner_training.xml',
        'views/promotional_details.xml',
        'views/coming_soon.xml',
        'views/creator_profile.xml',
        'views/partner_profile.xml',
        'views/customer_profile.xml',
        'views/customer_support.xml',
        'views/userblock_template.xml',
        'views/partner_master.xml',
        'views/partner_video1.xml',
        'views/partner_video2.xml',
        'views/partner_video3.xml',
        'views/partner_term.xml',
        'views/partner_welcome.xml',
        'views/payment_page_cart.xml',
        'views/partner_promotional_consume.xml',
        'views/loyalty_program.xml',
        'views/create_course_detail.xml',
        'views/create_course_standard.xml',
        # 'views/blog_post_views.xml',
        'data/email_templates.xml'
    ],
    # 'assets': {
    #     'web.assets_frontend': [
    #         'custom_web_kreator/static/src/css/custom_styl.css',
    #     ]},

    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
